name: Build & Create GitHub Release
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write # Required to create releases

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    needs: [build-check]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
      - name: Determine If Release Necessary
        id: determine-if-release-necessary
        run: |
          SHOULD_RELEASE=$(dotnet ./iac/should-release.cs)
          echo "Command output: $SHOULD_RELEASE"
          echo "should_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT
      - uses: chickensoft-games/setup-godot@v2
        if: steps.determine-if-release-necessary.outputs.should_release == 'true'
        with:
          version: 4.6.1
          use-dotnet: true
          include-templates: true
      - name: Dotnet Run Pipeline
        if: steps.determine-if-release-necessary.outputs.should_release == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet run -c Release --project ./iac/Deploy/Deploy.csproj
